gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    user_provider: app_user_provider
    user_identity_field: id
    token_parameter_name: refresh_token
    ttl: 2592000
    ttl_update: true
    single_use: true
